# Generated by Django 4.2.5 on 2023-09-19 18:27

from django.db import migrations

from db_pocedure.booking_procedure import (BUY_MOVIE_TICKET_PROCEDURE,
                                           DROP_BUY_MOVIE_TICKET_PROCEDURE)


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=BUY_MOVIE_TICKET_PROCEDURE,
            reverse_sql=DROP_BUY_MOVIE_TICKET_PROCEDURE
        ),
    ]
